/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On Mar 11, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.exception;

/**
 * @author Ankit
 *
 */
public class NoSuchCollection extends ServiceException {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

}
