/**
 * This file is generated by Ankit Singh Katiyar 
 * Generated On Mar 11, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.exception;

/**
 * @author Ankit
 *
 */
public class NoSuchElementException extends ServiceException {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     */
    public NoSuchElementException() {
        super();
        // TODO Auto-generated constructor stub
    }

    /**
     * @param message
     * @param cause
     */
    public NoSuchElementException(String message, Throwable cause) {
        super(message, cause);
        // TODO Auto-generated constructor stub
    }

    /**
     * @param message
     */
    public NoSuchElementException(String message) {
        super(message);
        // TODO Auto-generated constructor stub
    }

    /**
     * @param cause
     */
    public NoSuchElementException(Throwable cause) {
        super(cause);
        // TODO Auto-generated constructor stub
    }

}
