/**
 * This file is generated by Ankit Singh Katiyar 
 * Generated On Mar 11, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.exception;

/**
 * @author Ankit
 * 
 */
public class PendingTaskException extends ServiceException {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    @Override
    public String getMessage() {
        if (super.getMessage() == null) {
            return "One task is already in progress";
        }
        return super.getMessage();
    }

    /**
     * 
     */
    public PendingTaskException() {
        super();
        // TODO Auto-generated constructor stub
    }

    /**
     * @param message
     * @param cause
     */
    public PendingTaskException(String message, Throwable cause) {
        super(message, cause);
        // TODO Auto-generated constructor stub
    }

    /**
     * @param message
     */
    public PendingTaskException(String message) {
        super(message);
        // TODO Auto-generated constructor stub
    }

    /**
     * @param cause
     */
    public PendingTaskException(Throwable cause) {
        super(cause);
        // TODO Auto-generated constructor stub
    }

}
