/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On Mar 21, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.service.impl;

import com.ankit.portal.service.dao.ReferenceDAO;
import com.ankit.portal.service.domain.Reference;

/**
 * @author Ankit
 *
 */
public class ReferenceImpl implements ReferenceDAO {

    @Override
    public Reference addReference(Reference reference) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public Reference updateReference(Reference reference) {
        // TODO Auto-generated method stub
        return null;
    }

}
