/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On Mar 26, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.service.util;

import java.util.List;

import com.ankit.portal.service.dao.PermissionDAO;
import com.ankit.portal.service.domain.Permission;
import com.ankit.portal.service.impl.PermissionImpl;

/**
 * @author Ankit
 * 
 */
public class PermissionUtil {

    private static final PermissionDAO DAO = new PermissionImpl();

    public static List<Permission> getPermissions() {
        return DAO.getPermissions();
    }

    public static List<Permission> getPermissions(Integer... ids) {
        return DAO.getPermissions(ids);

    }
    
    public static List<Permission> getPermissions(List<Integer> ids) {
        return DAO.getPermissions(ids);

    }

}
