/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On Mar 26, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.service.util;

import java.util.List;
import java.util.Set;

import com.ankit.portal.service.dao.UserDAO;
import com.ankit.portal.service.domain.Role;
import com.ankit.portal.service.domain.User;
import com.ankit.portal.service.domain.UserGroup;
import com.ankit.portal.service.impl.UserImpl;

/**
 * @author Ankit
 * 
 */
public class UserUtil {

    private static final UserDAO DAO = new UserImpl();

    public static User findByEmail(String email) {
        return DAO.findByEmail(email);
    }

    public static Set<Role> getRolesByUserId(Long userId) {
        return DAO.getRolesByUserId(userId);
    }

    public static User getUser(Long userId) {
        return DAO.getUser(userId);
    }

    public static User addUser(User user) {
        return DAO.addUser(user);
    }

    public static List<User> getUsers() {
        return DAO.getUsers();
    }

    public static Long getTotalUsers() {
        return DAO.getTotalUsers();
    }

    public static List<User> getUsers(Integer startIndex, Integer maxReocrds) {
        return DAO.getUsers(startIndex, maxReocrds);
    }

    public static void updateUser(User user) {
        DAO.updateUser(user);
    }

    public static List<User> getUsersLike(User user, Integer startIndex,
            Integer maxReocrds) {
        return DAO.getUsersLike(user, startIndex, maxReocrds);
    }

    public static Long getTotalUsersLike(User user) {
        return DAO.getTotalUsersLike(user);
    }

    public static List<UserGroup> getGroupByUserId(Long userId) {
        return DAO.getGroupByUserId(userId);
    }

    public static List<User> searchUser(String queryString, Integer startIndex,
            Integer maxReocrds) {
        return DAO.searchUser(queryString, startIndex, maxReocrds);
    }

    public static Integer searchUserCount(String queryString) {
        return DAO.searchUserCount(queryString);
    }
}
