/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On Mar 21, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.service.dao;

import java.util.List;

import com.ankit.portal.service.domain.Article;
import com.ankit.portal.support.StatusType;

/**
 * @author Ankit
 * 
 */
public interface ArticleDAO {

    Article addArticle(Article article);

    List<Article> getArticles(Integer startIndex, Integer maxRecords);
    
    List<Article> getLatestArticles(Integer startIndex, Integer maxRecords);
    
    Long getTotalArticles();
    
    Long getTotalLatestArticles();

    Article getArticle(Long articleId);
    
    List<Article> getArticlesByUUID(String uuid,Integer startIndex, Integer maxRecords);
    
    Long getTotalArticlesByUUID(String uuid);

    Article updateArticle(Article article);
    
    Article fetchArticleByTitle(String articleTitle);
    
    List<Article> fetchArticlesByTitle(String articleTitle,Integer startIndex, Integer maxRecords);
    
    Article getLatestVersionByUUID(String uuid);
    
    Article getLatestVersionByArticleId(Long id);
    
    Article publishArticle(Long articleId); 
    
    void deleteArticle(Long articleId);
    
    Article getLatestVersionArticleByUUIDStatus(String uuid,StatusType statusType);
    
    List<Article> searchArticle(String queryString,StatusType statusType,Integer startIndex, Integer maxReocrds);
    
    Long searchArticleCount(String queryString,StatusType statusType);
}
