/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On Mar 21, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.service.dao;

import java.util.List;

import com.ankit.portal.exception.NoSuchElementException;
import com.ankit.portal.exception.PermissionLacks;
import com.ankit.portal.service.domain.Permission;
import com.ankit.portal.service.domain.Role;

/**
 * @author Ankit
 * 
 */
public interface RoleDAO {

    /**
     * This will return all the Roles
     * 
     * @return {@link List}<{@link Role}>
     */
    List<Role> getRoles();

    /**
     * Get a {@link Role} object by it;s id
     * 
     * @param roleId
     * @return {@link Role}
     */
    Role getRole(Integer roleId);

    /**
     * Add a new {@link Role}
     * 
     * @param role
     * @return the generated identifier
     */
    Integer addRole(Role role);

    /**
     * Update an existing {@link Role}
     * 
     * @param role
     */

    Long getRoleCount();

    List<Role> getRoles(Integer startIndex, Integer totalRecords);

    Integer addRole(String roleName, Long createdBy, Boolean modifiable);

    void updateRole(Role role, Long updatingUserId) throws PermissionLacks;
    
    void deleteRole(Integer roleId,Long userId) throws NoSuchElementException,PermissionLacks, Exception;
    
    List<Role> getRoles(Integer... roleIds);
    
    List<Permission> loadPermissions(Integer roleId);
}
