/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On Mar 23, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.service.domain;

import java.io.Serializable;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.ankit.portal.support.MessageType;

/**
 * {@link AdminMessage} are requests/feedbacks for any access or changes from
 * {@link User} to Admin
 * 
 * @author Ankit
 * 
 */
@Entity(name="AdminMessage")
@Table(name="admin_message")
@Cacheable(value=true)
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
public class AdminMessage implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "message_id")
    private Long id;

    @ManyToOne(optional = false, targetEntity = User.class)
    @JoinColumn(name = "user_id")
    private User from;

    @Column(length = 500, nullable = false)
    private String message;

    @Column(nullable = false,name="_read")
    private boolean read = false;

    @Enumerated(EnumType.STRING)
    @Column(nullable=false)
    private MessageType messageType=MessageType.FEEDBACK;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getFrom() {
        return from;
    }

    public void setFrom(User from) {
        this.from = from;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public boolean isRead() {
        return read;
    }

    public void setRead(boolean read) {
        this.read = read;
    }

    public MessageType getMessageType() {
        return messageType;
    }

    public void setMessageType(MessageType messageType) {
        this.messageType = messageType;
    }

}
