/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On Mar 23, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.service.domain;

import java.io.Serializable;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * {@link Notification} are alerts to users for any event
 * @author Ankit
 *
 */
@Entity(name="Notification")
@Table(name="notification")
@Cacheable(value=true)
@Cache(usage=CacheConcurrencyStrategy.READ_WRITE)
public class Notification implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="notification_id")
    private Long id;
 
    @ManyToOne(optional=false,targetEntity=User.class)
    @JoinColumn(name="user_id")
    private User to;
    
    @Column(length=200,nullable=false)
    private String message;
    
    @Column(nullable=false)
    private boolean read=false;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public User getTo() {
        return to;
    }

    public void setTo(User to) {
        this.to = to;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public boolean isRead() {
        return read;
    }

    public void setRead(boolean read) {
        this.read = read;
    }   
    
    
}
