/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On 10-Apr-2014 for the web application of a portal project
 */
package com.ankit.portal.util;

import org.apache.shiro.crypto.hash.Sha256Hash;

/**
 * @author Ankit
 *
 */
public class EncryptUtil {
	
	public static String encryptPassword(String password){
		return new Sha256Hash(password).toBase64();
	}

}
