/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On 10-Apr-2014 for the web application of a portal project
 */
package com.ankit.portal.util;


/**
 * Util class for the portal
 * @author Ankit
 * 
 */
public class Util {
	
	public static final String DATE_FORMAT = "dd-MM-yyyy";
	
	public static final String DATE_TIME_FORMAT = "dd-MM-yyyy hh:mm:ss a";
}
