/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On Mar 27, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.service.test;

import com.ankit.portal.service.util.UserGroupUtil;

/**
 * @author Ankit
 *
 */
public class HQLTest {

    /**
     * @param args
     */
    public static void main(String[] args) {
      /* Session session=HibernateUtil.getSession();
       User user= (User)session.load(User.class, 1L);
      // org.hibernate.Query query=session.createQuery("select u.roles from User u where u.id=?");
       //query.setParameter(0, new Long(2L));
      // System.out.println(((Role)query.list().get(0)).getName());
      //System.out.println(user.getRoles());
       System.out.println(user);
       System.out.println("get roles");
       System.out.println(user.getRoles());
       HibernateUtil.closeSession();*/
        Integer integer[]={1,2};
        /*System.out.println(RoleUtil.getRoles(integer));
        System.out.println(RoleUtil.loadPermissions(1));
        System.out.println(UserUtil.getTotalUsers());*/
        System.out.println(UserGroupUtil.getTotalRoles(2L));

       
        
    

    }

}
