/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On Mar 26, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.service.test;

import org.hibernate.Session;

import com.ankit.portal.hibernate.util.HibernateUtil;
import com.ankit.portal.service.domain.Permission;

/**
 * @author Ankit
 *
 */
public class PermissionTest {

    /**
     * @param args
     */
    public static void main(String[] args) {
        Permission permission=new Permission();
        permission.setName("cpanel:view");
Session session=       HibernateUtil.getSession();
session.beginTransaction();
session.save(permission);
session.getTransaction().commit();
HibernateUtil.closeSession();

    }

}
