/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On Mar 23, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.support;

/**
 * @author Ankit
 *
 */
public enum MessageType {

    REQUEST,FEEDBACK
}
