/**
 * This file is generated by Ankit Singh Katiyar
 * Generated On Mar 2, 2014 for the hibernate services of a portal project
 */
package com.ankit.portal.support;

/**
 * This enumeration defines the type of any Entity
 * @author Ankit
 * 
 *  
 */
public enum StatusType  {
    PUBLISHED, SAVE, UPDATED
}
